name: neural-ot
channels:
    - nvidia
    - conda-forge
    - bioconda
dependencies:
    - python
    - cmake
    - numpy
    - pandas
    - matplotlib
    - scipy
    - scikit-learn
    - cudatoolkit=11.4.1
    - cuda-nvcc
    - jaxlib=0.3.14=cuda112py39h867d1ad_203
    - jax=0.3.14
    - tensorflow
    - flax=0.5.2
    - optax=0.1.3
    - h5py
    - numba
    - anndata
    - scanpy
    - scvelo
    - umap-learn
    - mpi4py
    - petsc4py
    - slepc4py
    - tbb=2020.2
    - jupyter
    - wandb
    - pip
    - pip:
          - ott-jax==0.2.8
          - git+https://github.com/theislab/cellrank@master
          - tueplots
