seml:
    executable: train.py
    name: pancreas_1415_pmm
    output_dir: runs/logs
    project_root_dir: ../..

slurm:
    sbatch_options_template: GPU

fixed:
    init:
        exp_name: pancreas_1415_pmm
    data:
        target_type: anndata_paired
        source_type: anndata_paired
        source_params:
            use_pca: True
            batch_size: 1024
            adata_path_source: data/pancreas/day_14.5_growth_rate.h5ad
            adata_path_target: data/pancreas/day_15.5_growth_rate.h5ad
            matching: False
        target_params:
            use_pca: True
            batch_size: 1024
    model:
        model_type: icnn
        activation: leaky_relu
        model_params:
            dim_hidden: [64, 64, 64, 64]
            pos_weights: False
            first_quadratic: True
            first_quadratic_term: False
            last_quadratic_term: False
            closed_form_init: False
            dim_data: 50

    optimization:
        optimizer_type: adam
        schedule: False
        optimizer_params:
            learning_rate: 0.001
            beta_one: 0.5
            beta_two: 0.9
            clip_grad_norm: 1.0
            weight_decay: 0.0
    solver:
        solver_type: makkuva
        solver_params:
            input_dim: 50
            wandb_logging: True
            pos_weights: False
            beta: 1.0
            pretrain: True
            metric: sinkhorn_forward
    training.training_params:
        iterations: 15000
        inner_iters: 10
        valid_freq: 250
        log_freq: 1
        matching_loaders: True
